spring:
  application:
    name: sistema-escolar
  jpa:
    Hibernate:
      ddl-auto: none
    show_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_academico
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    validation-query: SELECT 1

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: sistema_academico