server:
  error:
#    include-stacktrace: on_param

spring:
  jpa:
    Hibernate:
      ddl-auto: none
    show_sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect
  datasource:
#    url: jdbc:mysql://localhost:3306/aluno?serverTimezone=UTC&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/sistema_academico
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    validation-query: SELECT 1

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean_disabled: true
#    validate-on-migrate: false
    schemas: sistema_academico