CREATE DATABASE IF NOT EXISTS sistema_academico;
USE sistema_academico;

CREATE TABLE aluno (
    ID_ALUNO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF CHAR(11) UNIQUE NOT NULL,
    MATRICULA VARCHAR(17) UNIQUE NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    SEXO ENUM('M', 'F', 'OUTRO') NOT NULL,
    NOME_MAE VARCHAR(100) NOT NULL,
    NOME_PAI VARCHAR(100) NOT NULL,
    SITUACAO_MATRICULA ENUM('ATIVO', 'INATIVO', 'PENDENTE') NOT NULL,
    CURSO VARCHAR(50) NOT NULL
);

CREATE TABLE enedereco (
    ID_ENDERECO BIGINT AUTO_INCREMENT PRIMARY KEY,
    RUA VARCHAR(150) NOT NULL,
    CIDADE VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    CEP CHAR(8) NOT NULL,
    NUMERO VARCHAR(7) NOT NULL,
    ID_ALUNO BIGINT,
    FOREIGN KEY (ID_ALUNO) REFERENCES aluno(ID_ALUNO) ON DELETE CASCADE
);

CREATE TABLE professor (
    ID_PROFESSOR BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF CHAR(11) UNIQUE NOT NULL,
    SEXO ENUM('Masculino', 'Feminino', 'Outro') NOT NULL,
    TELEFONE VARCHAR(15),
    EMAIL VARCHAR(100) UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    MATRICULA VARCHAR(20) UNIQUE NOT NULL,
    SITUACAO_MATRICULA ENUM('ATIVO', 'INATIVO', 'PENDENTE') NOT NULL,
    SALARIO DECIMAL(10,2) NOT NULL
);

CREATE TABLE disciplina (
    ID_DISCIPLINA BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    SITUACAO_DISCIPLINA ENUM('ATIVO', 'INATIVO', 'PLANEJAMENTO') NOT NULL,
    ID_PROFESSOR BIGINT,
    FOREIGN KEY (ID_PROFESSOR) REFERENCES professor(ID_PROFESSOR) ON DELETE SET NULL
);

CREATE TABLE rel_alun_disc (
    REL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_ALUNO BIGINT,
    ID_DISCIPLINA BIGINT,
    FOREIGN KEY (ID_ALUNO) REFERENCES aluno(ID_ALUNO) ON DELETE CASCADE,
    FOREIGN KEY (ID_DISCIPLINA) REFERENCES disciplina(ID_DISCIPLINA) ON DELETE CASCADE
);

CREATE TABLE avaliacao (
    ID_AVALIACAO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ID_DISCIPLINA BIGINT,
    NOTA DECIMAL(2,1),
    DATA_HORA DATETIME NOT NULL,
    LOCAL VARCHAR(100) NOT NULL,
    FOREIGN KEY (ID_DISCIPLINA) REFERENCES disciplina(ID_DISCIPLINA) ON DELETE CASCADE
);

CREATE TABLE notas (
    ID_NOTA BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_AVALIACAO BIGINT,
    VALOR_NOTA DECIMAL(2,1) NOT NULL,
    FOREIGN KEY (ID_AVALIACAO) REFERENCES avaliacao(ID_AVALIACAO) ON DELETE CASCADE
);
